### ISSUE TITLE
Pas de choix de star à l'édition du profil

### ISSUE THREAD

**Issue by superkebab** [M2DLG4/JackiesEtSosies#55]
Quand le membre est déjà sosie et qu'il veut éditer son profil, il n'y a pas le dropdown. Il faut cocher et décocher pour qu'il apparaisse :/

**Comment by bzzd31** [comment]
Lorsque qu'un membre sosie édite son profil et qu'il valide directement, il y a une erreur car le dropdown a la valeur "" par défaut, une erreur est donc envoyé.
